// <auto-generated />
using System;
using Acessly.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Acessly.Migrations
{
    [DbContext(typeof(AcesslyDbContext))]
    [Migration("20251116201140_FixOracleMapping")]
    partial class FixOracleMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acessly.Domain.Entities.Candidato", b =>
                {
                    b.Property<long>("IdCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CANDIDATO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCandidato"));

                    b.Property<string>("AcessibilidadeNecessaria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ACESSIBILIDADE_NECESSARIA");

                    b.Property<string>("Experiencia")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EXPERIENCIA");

                    b.Property<string>("Habilidades")
                        .HasColumnType("CLOB")
                        .HasColumnName("HABILIDADES");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("TipoDeficiencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_DEFICIENCIA");

                    b.HasKey("IdCandidato");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("CANDIDATO", (string)null);
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Candidatura", b =>
                {
                    b.Property<long>("IdCandidatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CANDIDATURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCandidatura"));

                    b.Property<DateTime>("DataCandidatura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CANDIDATURA");

                    b.Property<long>("IdCandidato")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CANDIDATO");

                    b.Property<long>("IdVaga")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VAGA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("EmAnalise")
                        .HasColumnName("STATUS");

                    b.HasKey("IdCandidatura");

                    b.HasIndex("IdCandidato");

                    b.HasIndex("IdVaga");

                    b.ToTable("CANDIDATURA", (string)null);
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Empresa", b =>
                {
                    b.Property<long>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EMPRESA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEmpresa"));

                    b.Property<string>("Descricao")
                        .HasColumnType("CLOB")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("IdUsuario")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("NivelAcessibilidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NIVEL_ACESSIBILIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("SETOR");

                    b.Property<string>("Site")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SITE");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("EMPRESA", (string)null);
                });

            modelBuilder.Entity("Acessly.Domain.Entities.SuporteEmpresa", b =>
                {
                    b.Property<long>("IdSuporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SUPORTE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSuporte"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<string>("TipoSuporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_SUPORTE");

                    b.HasKey("IdSuporte");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("SUPORTE_EMPRESA", (string)null);
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_USUARIO");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Vaga", b =>
                {
                    b.Property<long>("IdVaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_VAGA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdVaga"));

                    b.Property<string>("AcessibilidadeOferecida")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ACESSIBILIDADE_OFERECIDA");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Descricao")
                        .HasColumnType("CLOB")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESTADO");

                    b.Property<long>("IdEmpresa")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<decimal?>("Salario")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("SALARIO");

                    b.Property<string>("TipoVaga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_VAGA");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TITULO");

                    b.HasKey("IdVaga");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("VAGA", (string)null);
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Candidato", b =>
                {
                    b.HasOne("Acessly.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Candidato")
                        .HasForeignKey("Acessly.Domain.Entities.Candidato", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Candidatura", b =>
                {
                    b.HasOne("Acessly.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Candidaturas")
                        .HasForeignKey("IdCandidato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CANDIDATURA_CANDIDATO");

                    b.HasOne("Acessly.Domain.Entities.Vaga", "Vaga")
                        .WithMany("Candidaturas")
                        .HasForeignKey("IdVaga")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CANDIDATURA_VAGA");

                    b.Navigation("Candidato");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Empresa", b =>
                {
                    b.HasOne("Acessly.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Empresa")
                        .HasForeignKey("Acessly.Domain.Entities.Empresa", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Acessly.Domain.Entities.SuporteEmpresa", b =>
                {
                    b.HasOne("Acessly.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Suportes")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SUPORTE_EMPRESA");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Vaga", b =>
                {
                    b.HasOne("Acessly.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VAGA_EMPRESA");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Suportes");

                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Candidato");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Acessly.Domain.Entities.Vaga", b =>
                {
                    b.Navigation("Candidaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
